server:
  port: 8080

spring:
  application:
    name: cis-study-backend

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/study_abroad?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto